OCaml+ADT | Interpreter | Kirill Shishin
Kakadu/fp2023 pull request #107
Opened 2024-01-08 23:46 UTC by tepa46

Infer will be added later

2024-01-09 14:32 UTC, Kakadu commented on Ocaml+ADT/lib/ast.ml
> +  | PCase of decl_name * pattern (* Tepa 46 *)
Это значите непонятно что

2024-01-09 14:34 UTC, Kakadu commented on Ocaml+ADT/lib/interpreter.ml
> +    | _ -> fail PatternMatchingError
копипаста.

2024-01-09 14:37 UTC, Kakadu commented on Ocaml+ADT/demos/demoInterpret.t
> +  $ dune exec demoInterpret << EOF
А почему у вас дюна в тестах?

2024-01-09 14:38 UTC, Kakadu requested changes
У меня ощущение, что содержимое не вполне соответствует условию задачи

2024-01-09 16:45 UTC, tepa46 commented on Ocaml+ADT/lib/ast.ml
> +  | PCase of decl_name * pattern (* Tepa 46 *)
Согласен, комментарий в коде совсем непонятен.  Это паттерн для алгебраических типов. В новом коммите комментарий исправил

2024-01-09 16:50 UTC, tepa46 commented on Ocaml+ADT/lib/interpreter.ml
> +    | _ -> fail PatternMatchingError
Да, здесь `match` написан не очень хорошо. В нем можно использовать только один `fail`, вместо двух. В новом коммите переписал этот `match` и некоторые другие.

2024-01-09 16:53 UTC, tepa46 commented on Ocaml+ADT/demos/demoInterpret.t
> +  $ dune exec demoInterpret << EOF
А почему это плохо? Мне показалось это довольно легким и красивым решением. Я его использовал еще в ноябре, когда тестировал парсер.

2024-01-09 19:17 UTC, Kakadu commented on Ocaml+ADT/demos/demoInterpret.t
> +  $ dune exec demoInterpret << EOF
Зачем он там?

2024-01-09 19:18 UTC, Kakadu commented on Ocaml+ADT/lib/ast.ml
> +  | PAdt of decl_name * pattern (* pattern for ADT types: Tree(_, _) *)
Меня таки смущает decl_name

2024-01-09 19:19 UTC, Kakadu commented on Ocaml+ADT/lib/ast.ml
> +  | EEmptyList
Почему тут и пустой список, и алгебраичесое значение?

2024-01-09 19:24 UTC, Kakadu commented on Ocaml+ADT/lib/interpreterTypes.ml
> +  | VLetRec of string * value
Не очень  понятна разница между последними двумя.

2024-01-09 19:25 UTC, Kakadu commented on Ocaml+ADT/lib/tests/interpreterTests.ml
> +  in
Я про строковы литералы рассказывал, а Вы всё заигнорили.

2024-01-09 19:26 UTC, Kakadu commented
> > У меня ощущение, что содержимое не вполне соответствует условию задачи
> 
> Поддержаны алгебраические типы как основной способ проектирования типов: объявление собственных алгебраических типов и использование их в программе. Также поддержан паттерн-мэтчинг алгебраических типов. Возможно я что-то упустил?

Никаких объявлений алгебраических типов я не нашел.

2024-01-15 03:02 UTC, tepa46 commented on Ocaml+ADT/lib/tests/interpreterTests.ml
> +  in
Виноват( Исправил

2024-01-15 03:05 UTC, tepa46 commented on Ocaml+ADT/lib/interpreterTypes.ml
> +  | VLetRec of string * value
По сути VLetRec используется как обертка над VFun и позволяет интерпретировать рекурсивные функции.

2024-01-15 03:11 UTC, tepa46 commented on Ocaml+ADT/lib/ast.ml
> +  | PAdt of decl_name * pattern (* pattern for ADT types: Tree(_, _) *)
```
type decl_name =
  | LName of string (* abc, aBc *)
  | UName of string (* Number *)
```
LName используется для всех деклараций.
UName используется именно для алгебраических типов. 
В случае PAdt парсер положит в decl_name именно UName. То есть, для adt паттетна на примере Tree (a, b) будет такая структура: PAdt(UName "Tree", ...)

2024-01-15 03:22 UTC, tepa46 commented on Ocaml+ADT/lib/ast.ml
> +  | EEmptyList
В моей реализации exp списка записывается через binop Cons. То есть все списки выглядят как `EBinop(Cons, EInt 4, EBinop (Cons, EInt 5, EBinop (Cons, EInt 6, EEmptyList)))`
При помощи Cons никак не представить пустой список, поэтому я использую специальный тип EEmptyList.

2024-01-15 03:41 UTC, tepa46 commented on Ocaml+ADT/demos/demoInterpret.t
> +  $ dune exec demoInterpret << EOF
Для того, чтобы исполнить тест. Конечно, там можно обойтись без и дюны, но я решил сделать с ней.

2024-01-15 03:53 UTC, tepa46 commented
Ответил на Ваши комментарии.
Добавил тесты с объявлением алгебраических типов.
Добавил инфер, поддерживающий алгебраические типы.

2024-01-15 17:12 UTC, Kakadu commented
Я там стрёмный пример хотел написать, но у вас там синтаксические ошибки похоже вообще не соощаются. Разебритесь.

2024-01-15 17:13 UTC, Kakadu commented on Ocaml+ADT/lib/ast.ml
>    | TEmptyType
Комментарии к этому типу нужны. Я без понятия что имеется в виду.

2024-01-15 17:15 UTC, Kakadu commented on Ocaml+ADT/lib/ast.ml
> +  | PAdt of decl_name * pattern option (* pattern for ADT types: Tree(_, _) *)
Прочитайте условие

2024-01-15 17:22 UTC, Kakadu commented on Ocaml+ADT/lib/inferencer.ml
> +
Списано с меня?)

2024-01-15 17:26 UTC, tepa46 commented on Ocaml+ADT/lib/ast.ml
> +  | PAdt of decl_name * pattern option (* pattern for ADT types: Tree(_, _) *)
Это вы про то, что я использую PCons для списков, а не алгебраический тип?

2024-01-15 17:27 UTC, Kakadu commented on Ocaml+ADT/lib/inferencer.ml
> +  | _ -> return env
Почему env?

2024-01-15 17:29 UTC, tepa46 commented on Ocaml+ADT/lib/inferencer.ml
> +  | _ -> return env
Тут должен быть fail. Исправлю в новом коммите

2024-01-15 17:37 UTC, Kakadu commented on Ocaml+ADT/lib/inferencer.ml
> +let rec convert_type (typ : Ast.decl_type) =
Я не очень понял смысл этой функции

2024-01-15 17:39 UTC, Kakadu commented on Ocaml+ADT/demos/demoInference.t
> +  > let n = fun a :: b -> a
По-моему, это должно быть syntax error

2024-01-15 17:40 UTC, Kakadu commented on Ocaml+ADT/demos/demoInference.t
> +  $ dune exec demoInference << EOF
А зачем дюна в тестах?

2024-01-15 17:41 UTC, tepa46 commented on Ocaml+ADT/lib/inferencer.ml
> +let rec convert_type (typ : Ast.decl_type) =
Она конвертирует Ast тип в тип, который используется в инфере. Это используется в функции ниже для добавления алгебраического типа в adt_env сразу с конвертированными типами. Это удобно для дальнейшего использования adt_env в инфере.

2024-01-15 17:44 UTC, tepa46 commented on Ocaml+ADT/lib/inferencer.ml
> +
Ваше решение использовалось только как шаблон. 
- Был произведен некоторый рефакторинг (включая замену листов на мапы)
- Добавлено все, что нужно в рамках моей задачи

2024-01-15 17:44 UTC, Kakadu commented on Ocaml+ADT/demos/demoInference.t
> +  > type typ2 = | Num of typ1 | Str of string
я так понял на полиморфизм шансов нет?

2024-01-15 17:48 UTC, tepa46 commented on Ocaml+ADT/demos/demoInference.t
> +  > let n = fun a :: b -> a
utop это понимает, правда только со скобочками. 
![image](https://github.com/Kakadu/fp2023/assets/73890886/a034a5b7-0db3-4090-bbf2-13d615dded6f)

2024-01-15 17:53 UTC, tepa46 commented on Ocaml+ADT/demos/demoInference.t
> +  > type typ2 = | Num of typ1 | Str of string
В рамках алгебраических типов полиморфизм не поддержан(

2024-01-15 17:54 UTC, Kakadu commented on Ocaml+ADT/demos/demoInterpret.ml
> +;;
Многословно. Если бы вы осмыслили код типовыводилки полностью, то такое бы не написали.

2024-01-15 17:54 UTC, Kakadu commented on Ocaml+ADT/demos/demoInterpret.t
> +  $ dune exec demoInterpret << EOF
Сделайте нормально.

2024-01-15 17:56 UTC, tepa46 commented on Ocaml+ADT/demos/demoInterpret.ml
> +;;
На самом деле после того, как отработал infer, из интерпретации у меня может прийти только ошибка деления на 0. Но я решил оставить вывод того, откуда приходит ошибка

2024-01-15 18:05 UTC, Kakadu commented on Ocaml+ADT/demos/demoInterpret.ml
> +;;
1. Это всё равно многословно
2. Наверняка неполный метчинг тоже может вывалиться

2024-01-15 18:07 UTC, tepa46 commented on Ocaml+ADT/demos/demoInterpret.ml
> +;;
Да, неполный метчинг тоже может вывалиться. 
Хорошо, я уберу пометки о том, откуда приходит ошибка

2024-01-15 21:38 UTC, tepa46 commented on Ocaml+ADT/demos/demoInference.t
> +  $ dune exec demoInference << EOF
В новом коммите сделал без дюны

2024-01-15 21:38 UTC, tepa46 commented on Ocaml+ADT/demos/demoInterpret.t
> +  $ dune exec demoInterpret << EOF
В новом коммите сделал без дюны

2024-01-16 02:44 UTC, tepa46 commented on Ocaml+ADT/lib/ast.ml
>    | TEmptyType
Добавил в новом коммите

2024-01-16 03:35 UTC, tepa46 commented
* Переделал cram тесты. Теперь в них не используется дюна.
* Исправил ошибку с выводом ошибки парсинга. Оставил этот тест в `demoInterpret`.
 ```OCaml
let rec fix f x = f (fix f) x
let map f p = let (a,b) = p in (f a, f b)
let fixpoly l =
   fix (fun self l -> map (fun li x -> li (self l) x) l) l
let feven p n =
   let (e, o) = p in
   if n == 0 then 1 else o (n - 1)
let fodd p n =
   let (e, o) = p in
   if n == 0 then 0 else e (n - 1)
let tie = fixpoly (feven, fodd)
   let rezult =
let (even,odd) = tie in (odd 1)
 ```
   Также привел код этого теста к виду, который умеет кушать мой парсер и добавил его в `demoParse`, `demoInference` и `demoInterpret`.
* На счет теста с таким кодом:
```OCaml
let eq = fun a -> (fun b -> a = b)
let answ = eq  (1 :: []) (1 :: [])
```
Он не работал из-за того, что интерпетатор поддерживал операцию `Equals` только для `int` и `string`.
Добавил операцию `Equals` для списков, тюплов и алгебраических типов. Тест, соответственно, теперь исполняется успешно.
* На счет теста с таким кодом:
```OCaml
type list = | Nil | Cons of list
let rec x = Cons x
```
Моя реализация интерпретатора поддерживает рекурсивные функции, принимающие хотя бы один аргумент, либо являющиеся "мнимыми" рекурсивными функциями, например:
```
> let rec fix = fun f -> (fun x -> f (fix f) x)
"fix": '2 '3 . (('2 -> '3) -> '2 -> '3) -> '2 -> '3 = <rec fun>

> let rec n = 5
"n": int = 5
``` 
На тест выше `utop` выдает:
```
val x : list = Cons <cycle>
```
Такое точно нужно поддерживать?

2024-01-16 16:21 UTC, Kakadu commented on Ocaml+ADT/lib/ast.ml
>    | TEmptyType
Во-первых, понятней не стало.
Во вторых, у вас плохие значения представимы в типах (из-за  decl_name )

2024-01-16 17:24 UTC, Kakadu commented
![image](https://github.com/Kakadu/fp2023/assets/438226/34cc4fa9-4661-43e7-a629-73b6838239d1)

2024-01-16 17:25 UTC, tepa46 commented
Странно, у меня вот так
![image](https://github.com/Kakadu/fp2023/assets/73890886/04e8eac5-6568-4ed5-aebc-cb4e3809b0b2)
Попробую разобраться

2024-01-24 17:16 UTC, tepa46 commented
Теперь конфликтов не должно быть

2024-01-24 19:33 UTC, merged