Javascript | Arseniy Kuznetsov, Alexandr Shmakov
Kakadu/fp2023 pull request #117
Opened 2024-01-16 03:14 UTC by Kuarni

An interpreter for Javascript

Parser was partly rewrited
Implemented

- data types: Number, String, Null, Undefined, Bool, Objects (Arrays, Functions, Anon Functions, Arrow Functions)
- closures, recursion, assignment, prototype inheritance
- many things from WAT and wtfjs
- If, while, for
- console.log

2024-01-16 16:07 UTC, Kuarni commented on Javascript/lib/VTypes.mli
> +type lexical_env =
Не справедливо, в предложенном варианте все равно наблюдается взаимная рекурсия

2024-01-16 16:08 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    let var = { var_id = x.var_identifier; is_const = x.is_const; value = v } in
Не справедливо, x имеет отличный от var тип

2024-01-16 16:09 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    { stdout = ctx.stdout; return = ret }
Аналогично, это объект не типа ctx

2024-02-09 21:05 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    let var = { var_id = x.var_identifier; is_const = x.is_const; value = v } in
https://github.com/Kakadu/zanuda/issues/10

2024-02-09 21:05 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    { stdout = ctx.stdout; return = ret }
https://github.com/Kakadu/zanuda/issues/10

2024-02-11 15:40 UTC, Kakadu commented on Javascript/demos/demoObjects.ml
> +  \  console.log(obj2.prop2, obj2.getProp1(), obj2.prop1)"
Проигнорили всё что я говорил, про quoted string literals?

2024-02-11 15:41 UTC, Kakadu commented on Javascript/dune-project
> + ,
?

2024-02-11 15:45 UTC, Kakadu commented on Javascript/lib/ast.ml
> +      string list * statement (*objects like: (args)=>... or (args)=>{...}*)
А у этих двух функций разная семантика, что вы их в разные куски AST запихнули?

2024-02-11 16:22 UTC, Kakadu requested changes
> closures, recursion, assignment, prototype inheritance
Если правда есть, то надо тесты на факториал/фибоначчи с CPS и fixом.

И сделайте, чтобы в cram тестах код с терминала ввобдился, а не файл с программой, а то очень сложно тестировать.
И ещё надо рядом, чтобы эталонное исполнение nodejs было, а то сложно глазами все косяки JS учесть.

2024-02-11 19:17 UTC, Kuarni commented on Javascript/lib/ast.ml
> +      string list * statement (*objects like: (args)=>... or (args)=>{...}*)
Да, Anon и Arrow функции работают чуть по разному. Например, this у стрелочной функции берется из окружения в отличии от обычных функций.

2024-02-16 20:01 UTC, Kuarni commented on Javascript/demos/demoObjects.ml
> +  \  console.log(obj2.prop2, obj2.getProp1(), obj2.prop1)"
Не везде, но в demos да

2024-02-16 20:01 UTC, Kuarni commented on Javascript/dune-project
> + ,
Запятая была лишней

2024-02-16 20:02 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  | _ -> true
Этот код стал быстрой заменой для List.is_empty, чтобы была совместимость с OCaml версии 4.1

2024-02-17 15:04 UTC, Kakadu commented
Я ему написал `obj3.__proto__.prop2 = "asdf";`, а они орёт и я не могу расшифровать

> Error: Interpreter error > error in expression statement > error in assignment > SyntaxError: Invalid or unexpected token

2024-02-17 15:05 UTC, Kakadu commented
![image](https://github.com/Kakadu/fp2023/assets/438226/8c515d7b-dcb4-46f3-952d-8cf0c339c373)

2024-02-17 15:07 UTC, Kakadu commented on Javascript/lib/interpreter.ml
> +  | _ -> true
А зачем вам совместимость с 4.1, если оно соибрается в CI под 4.14?

2024-02-17 15:11 UTC, Kakadu commented on Javascript/lib/interpreter.ml
> +       | _ as x ->
Длинно

2024-02-18 12:53 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  | _ -> true
Чуть под обобщил до 4.1, делалось под совместимость как раз таки с 4.14 (List.is_empty появилось в 5.1)

2024-02-19 00:04 UTC, Kuarni commented
> Я ему написал `obj3.__proto__.prop2 = "asdf";`, а они орёт и я не могу расшифровать
> 
> > Error: Interpreter error > error in expression statement > error in assignment > SyntaxError: Invalid or unexpected token

Там была бага, поправил

2024-02-19 00:05 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +       | _ as x ->
Ладно

2024-02-21 09:25 UTC, Kakadu commented
> * js код demo вынес в отдельные js файлы, чтобы можно было запустить через node.js

Ну так добавьте вызов nodejs

2024-02-25 09:43 UTC, merged