Interpreter + Inferencer of miniOCaml | Akhmedov David
Kakadu/fp2023 pull request #121
Opened 2024-01-18 04:00 UTC by Parzival-05

Здравствуйте. Cо своей темой не разобрался. Выполнил в объеме на оценку "D". Следующим PR переименую. (С гитом неаккуратно работал, поэтому PR случайно закрылся и дублируется)

2024-02-05 18:15 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +  | ParseError
А как ошибка парсинга может получиться при интерпретации?

2024-02-05 18:17 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/demos/fact_demo.t
> +
Ещё стоило бы сделать тесты с CPS, чтобы и выходи выход в одном  .t файле был.

2024-02-05 18:21 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +
Код зверски похож на мой. Вам же про права и  лицензии должны были рассказывать?
К тому же используются фичи  языка, которые я в лекциях не рассказывал, а Вы в них наверняка не разобрались.
Напишите так, чтобы не выглядело списанным.

2024-02-05 18:34 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | GNil
GNil? нужны комментарии

2024-02-05 18:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | TVar var -> fprintf fmt "%s" ("'" ^ Char.escaped (Char.chr (var + 97)))
магические константы?

2024-02-05 18:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +        List.fold_left (fun _ typ -> fprintf fmt " * %a" pp_el typ) () tl
сложно

2024-02-05 18:36 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | UnificationFailed of typ * typ
В чем разница между 3 и 4м? нужны комменты.

2024-02-05 18:37 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/REPL.ml
> +  run_and_pp s
А зачем 2 одинаковых файла demo и REPL?

2024-02-07 13:24 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +  | ParseError
Упс. Переименовал конструктор.

2024-02-07 13:25 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +
Исправил это недоразумение :)

2024-02-07 13:26 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | GNil
По итогу не пригодилось, удалил конструктор

2024-02-07 13:27 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +        List.fold_left (fun _ typ -> fprintf fmt " * %a" pp_el typ) () tl
Переписал без фокусов

2024-02-07 13:28 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | UnificationFailed of typ * typ
Добавил комментарии

2024-02-07 13:36 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | TVar var -> fprintf fmt "%s" ("'" ^ Char.escaped (Char.chr (var + 97)))
Починил

2024-02-07 21:46 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +
Переименованием переменных?)

2024-02-07 21:49 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +  | ParseError
ParserAvoidedError? Лучше не стало.
Пишите документационные коменты.

2024-02-07 21:51 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/REPL.ml
> +  run_and_pp s
А стоило только его оставить...

2024-02-08 20:12 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +
Я использовал ваш вывод типов как шаблон, адаптировав под свою задачу. Мне казалось, что ничего криминального в этом нет. 

Сейчас "причесал" код: изменил переменные, чтобы везде были одинаковые там, где они совпадают по смыслу; переписал по-своему то, что можно, не обезобразив код. Как-то так.

2024-02-08 20:15 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +  | ParseError
Добавил

2024-02-11 10:42 UTC, Parzival-05 commented
Добавил печать и порефакторил инференс

2024-02-11 15:35 UTC, Kakadu requested changes
А оно могло стать ужаснее, чем в прошлый раз?
И сделайте уже линтеру хорошо.

2024-02-11 15:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +       | "_" -> return (env, twild)
Здесь нарушается 5й буллет условия.

2024-02-11 15:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/demos/demo.t
> +  val map_cps : ('z -> '{) -> 'z list -> ('{ list -> 'y) -> 'y = <fun>
Фигурные скобочки это что?

2024-02-11 15:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +  | ParserAvoidedError
???

2024-02-11 15:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | GWild (* Wildcard — _ *)
Это что такое?

2024-02-11 15:35 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | ParserAvoidedError
???

2024-02-11 21:35 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +       | "_" -> return (env, twild)
Как именно? Не понимаю, как это нарушает 5-й буллет

2024-02-11 21:36 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/demos/demo.t
> +  val map_cps : ('z -> '{) -> 'z list -> ('{ list -> 'y) -> 'y = <fun>
Особенность печати типов

2024-02-11 22:08 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/inferencer.ml
> +       | "_" -> return (env, twild)
Кажется, что понял

2024-02-11 22:08 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +  | ParserAvoidedError
Добавил комментарий

2024-02-11 22:20 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/typing.ml
> +  | ParserAvoidedError
Правда непонятен комментарий или что? Ниже написано:
"Use the parser to get the AST: the parser does some transformations of expressions" — парсер преобразует некоторые выражения в эквивалентные, чтобы меньше прописывать правила пришлось (хотя, откровенно говоря, не оказалось какой-то супероптимизацией). Н., `y >= x` в `x <= y`.

2024-02-12 11:31 UTC, Kakadu reviewed
По-придирался.

2024-02-12 11:31 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/demos/demo.t
> +  val map_cps : ('z -> '{) -> 'z list -> ('{ list -> 'y) -> 'y = <fun>
Это какая-то дичь. В камле такого нет.

2024-02-12 21:20 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +              else ())
Исправил печать

2024-02-14 14:15 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +    | PTuple (hd :: tl), VTuple (hd_v :: tl_v) ->
А почему тупл из 1 и 0 элементов, это вообще адекватно?

2024-02-14 14:34 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +    | PTuple (hd :: tl), VTuple (hd_v :: tl_v) ->
Тут рекурсия

2024-02-14 21:56 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +    | PTuple (hd :: tl), VTuple (hd_v :: tl_v) ->
И что?

2024-02-14 22:05 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +                 return
А правые части одинаковые или мне кажется? Оно вообще отличает одни примитивы от других?

2024-02-14 22:17 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +       | _ -> fail TypeError)
Вы пишите как на Котлине.

2024-02-15 08:11 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +                 return
Да, точно, исправил

2024-02-15 11:44 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/interpreter.ml
> +       | _ -> fail TypeError)
Переписал без котлина

2024-02-18 14:57 UTC, merged