OCamlWithEffects | Rafik Nurmuhametov, Dmitry Pilyuk
Kakadu/fp2023 pull request #138
Opened 2024-02-28 21:24 UTC by raf-nr

### OCaml with effects

Наш интерпретатор поддерживает базовые конструкции языка OCaml и обработку эффектов.

Поддерживаемые типы: `int`, `bool`, `char`, `string`, `unit`, `list`, `tuple`, `effect`.

Поддерживаемые конструкции: let-привязки, замыкания, арифметические операции, сопоставление с образцом, обработка эффектов, и т.д.

### Effects
Эффекты - это исключения, в момент обработки которых имеется функция, которая вернет значение, которое должно было бы быть вместо бросания исключения, и продолжит исполнение с места бросания исключения.

Объявить эффект можно с помощью ключевого слова `effect`, передав ему аннотацию типа. Эффект может принимать аргумент.
```ocaml
# effect E1 : int effect ;;
val E1 : int effect = <effect>

# effect E2 : int -> int effect ;;
val E2 : int -> int effect = <effect>
```

Вызвать эффект можно при помощи ключевого слова `perform`, передав ему эффект и аругмент (если эффект его принимает).
Для обработки вызванного эффекта используется блок `try with`.

```ocaml
# effect E : int -> int effect
# let result =
    try perform E 0 with
    | (E x) k -> continue k (x + 1)
;;

val E : int -> int effect = <effect>
val result : int = 1
```

Выражения внутри блока `try with` называются обработчиками эффектов. Все они должны в своей левой части "фиксировать" с помощью переменной продолжения место, откуда вызвался эффект. В правой части происходит непосредственно обработка эффекта, которая всегда должна в конечном итоге вызывать `continue k value` - таким образом, продолжая работу с место вызова эффекта. Здесь `value` - значение, которое подставится вместо "бросания" эффекта.

Это работает следующем образом: после `try` располагается любое выражение, внутри которого может быть вызван эффект. Если эффект внутри так и не был вызван, то результат интерпретации этого выражение и есть результат интерпретации блока `try with`. Если вдруг был вызван эффект, то он начинает сопоставляться с описаными в блоке обработчиками эффектов. Если подходящий обработчик не найден - возникнет ошибка, если найден - то в нашем случае "фиксируется" переменная `k`, символизирующая место, откуда вызван эффект и начинается его в обработка. В примере мы просто продолжаем выполнение, подставив вместо вызова эффекта значение, равное переданному в эффект числу + 1.

Более подробно с примерами обработки эффектов можно ознакомиться в `OCamlWithEffects/demos` и `OCamlWithEffects/tests`.

### Run
Запуск проверки типов и интерпретатора происходит из файла `run.ml`.
Функция `inference` парсит выражение, проверяет корректность полученного абстрактно-синтаксического дерева и запускает проверку типов с выводом результата.
Функция `interpret` делает все то, что делает предыдущая, после чего запускает интерпретацию программы с выводом результата.

2024-03-06 13:38 UTC, Kakadu requested changes
А у вас выразими примеры из мануала? https://v2.ocaml.org/manual/effects.html

AST ужасно

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/ast/ast.ml
> +  | EEffectDeclaration of id * effect_types_annotation
Это же не выражения, ни коем образом. Почему оно тут?

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inf_errors.ml
> +  | `Not_reachable (* Sections of code that will never be reached. *)
Мне интересно, как это можно проверить при проверке типов.

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inf_pprint.ml
> +           (fun ppf ty -> helper ppf ty))
длинно

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inf_pprint.ml
> +    | _ -> Format.printf "")
Скорее всего это неправильно

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +      | TTuple typ_list -> List.fold_left (fun acc item -> helper acc item) acc typ_list
длинно

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +    (match is_upper name.[0] with
""?

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +           | false -> name :: names_list
По-моему, это говнокод

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +       | _ -> fail not_reachable)
Bad design

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/typedtree.mli
> +  | TContinuePoint (* continue k 0 - here k type is continue point *)
?

2024-03-06 13:38 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/typedtree.mli
> +  val of_seq : elt Seq.t -> t
используйте include

2024-03-06 14:49 UTC, raf-nr commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +    (match is_upper name.[0] with
Я не понимаю, что вы хотите

2024-03-06 16:58 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +    (match is_upper name.[0] with
Почему строка не пустая?

2024-03-06 17:24 UTC, raf-nr commented on OCamlWithEffects/lib/ast/ast.ml
> +  | EEffectDeclaration of id * effect_types_annotation
Речь о всех декларейшенах или конкретно эффектах?

2024-03-06 21:03 UTC, raf-nr commented on OCamlWithEffects/lib/inferencer/inf_errors.ml
> +  | `Not_reachable (* Sections of code that will never be reached. *)
Запихать в инференс аст, которые вы написали сами, не используя парсер.
То есть если запускать все из run.ml - все будет нормально и подобное не будет достигнуто, а если вы напишите AST, которое парсер бы не пропустил, оно может попасть сюда.

2024-03-06 21:37 UTC, raf-nr commented on OCamlWithEffects/lib/inferencer/inf_errors.ml
> +  | `Not_reachable (* Sections of code that will never be reached. *)
Возможно действительно стоит поработать с названием и текстом ошибки, чтобы не было путаницы с одноименной ошибкой интерпретатора.

2024-03-07 07:47 UTC, Kakadu commented on OCamlWithEffects/lib/ast/ast.ml
> +  | EEffectDeclaration of id * effect_types_annotation
Всех

2024-03-07 07:49 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inf_errors.ml
> +  | `Not_reachable (* Sections of code that will never be reached. *)
> Запихать в inference программу (уже распаренную, AST), которую вы написали сами, не используя парсер.

Признак того, что Ast не годится

2024-03-08 18:16 UTC, raf-nr commented on OCamlWithEffects/lib/inferencer/inferencer.ml
> +           | false -> name :: names_list
Вы правы

2024-03-08 19:49 UTC, raf-nr commented on OCamlWithEffects/lib/inferencer/typedtree.mli
> +  | TContinuePoint (* continue k 0 - here k type is continue point *)
А в чем вопрос? Это тип, используемый для проверки, что "переменная продолжения" не перезаписалась.

Вот чтобы такое обрабатывать:

```ocaml
# effect E1 : int effect ;;
# let res = try perform E1 with | E1 k -> let k = 5 in continue k 0
```

2024-03-09 07:30 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/typedtree.mli
> +  | TContinuePoint (* continue k 0 - here k type is continue point *)
Он без аргументов,это странно

2024-03-09 11:41 UTC, raf-nr commented on OCamlWithEffects/lib/inferencer/typedtree.mli
> +  | TContinuePoint (* continue k 0 - here k type is continue point *)
Ниже используется тип TContinuation, который содержит аргумент - тип перекидываемого значения. А этот нужен просто для того, чтобы в enviroment'e хранить пару, допустим (k, TContinueProint), которая говорит о том, что k - переменная продолжения и когда мы наткнемся на continue k ..., он успешно выполнится.

2024-03-09 13:45 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/typedtree.mli
> +  | TContinuePoint (* continue k 0 - here k type is continue point *)
Почему оно без имени? У вас всегда один continuation?

2024-03-09 15:44 UTC, raf-nr commented
Если будет возможность принять работу в случае обнаружения недостатков со снижаем оценки до C - оба участника команды согласны!

2024-03-10 11:10 UTC, Kakadu approved these changes
> Если будет возможность принять работу в случае обнаружения недостатков со снижаем оценки до C - оба участника команды согласны!

У меня нет времени это читать, сделайте, чтобы rebasилось и будет С

2024-03-10 11:10 UTC, Kakadu commented on OCamlWithEffects/demos/demoComplexEffect.t
> +  Type error: unification failed - type continuation int does not match expected type int
Вам не кажется, что эта ошибка типизации не имеет смысла? Если этот код не принимается, то точно по другой причине

2024-03-10 11:10 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inf_errors.ml
> +  | `Handler_without_continue (* There is no continuation in the effect handler. *)
А почему должен быть?

2024-03-10 13:19 UTC, raf-nr commented on OCamlWithEffects/demos/demoComplexEffect.t
> +  Type error: unification failed - type continuation int does not match expected type int
Это связано с ответом ниже. Мы посчитали что нет смысла считать количество continue и возвращать ошибку (что нельзя больше 1 continue), потому что у нас может быть итак только 1 continue. 
А вот ошибка да, не очень красивая, возможно стоит обработать и возвращать `Handler_without_continue, хотя и это, наверное, не лучшая идея)

2024-03-10 13:20 UTC, raf-nr commented
Мы немного не поняли, то, что есть достаточно для C или нужно исправить новые замечания?
Вроде всё ребейзится.

2024-03-12 12:02 UTC, Kakadu commented
> Мы немного не поняли, то, что есть достаточно для C или нужно исправить новые замечания? Вроде всё ребейзится.

Достаточно

![image](https://github.com/Kakadu/fp2023/assets/438226/6e293926-6e0d-462b-980b-6dc2507bfd96)

2024-03-12 12:02 UTC, Kakadu commented on OCamlWithEffects/lib/inferencer/inf_errors.ml
> +  | `Handler_without_continue (* There is no continuation in the effect handler. *)
КРИНЖ

2024-03-12 12:03 UTC, Kakadu commented on OCamlWithEffects/demos/demoComplexEffect.t
> +  Type error: unification failed - type continuation int does not match expected type int
Я думаю оно  должно компилироваться, а множественные continue чекать в рантайме.

2024-03-12 12:41 UTC, closed without merging