MiniML | Ahmetov Temerlan
Kakadu/fp2023 pull request #141
Opened 2024-03-07 21:51 UTC by Lesh79

Работа выполнена с расчётом на оценку Е

2024-03-09 16:23 UTC, Kakadu requested changes
Не совсем понятно где тайпчекер.
И тестов мало. Надо бы ещё, как минимиум, тест, который объединяет CPSный факторал и комбинатор неподвижной точки

2024-03-09 16:23 UTC, Kakadu commented on DAhmetov/lib/interpret.ml
> +  KeyMap.iter (fun key data -> fprintf fmt "%s: %a\n" key pp_value data) enviroment
ДЛинно

2024-03-12 11:17 UTC, Lesh79 commented on DAhmetov/lib/interpret.ml
> +  let rec exec_var var env = find_decl var env
Переписал

2024-03-12 11:17 UTC, Lesh79 commented on DAhmetov/lib/interpret.ml
> +  ;;
написал fold

2024-03-12 12:47 UTC, Lesh79 commented on DAhmetov/lib/interpret.ml
> +  KeyMap.iter (fun key data -> fprintf fmt "%s: %a\n" key pp_value data) enviroment
Теперь менее "ДЛинно"

2024-03-14 09:21 UTC, Kakadu requested changes

2024-03-14 09:21 UTC, Kakadu commented on DAhmetov/lib/interpret.ml
> +  let extend_env arg_name arg_value env = KeyMap.add arg_name arg_value env
Длинно?

2024-03-14 09:21 UTC, Kakadu commented on DAhmetov/demos/demoInterpret.t
> +  > EOF
По-моему этот тест не совсем то, что я просил.

2024-03-14 09:41 UTC, Lesh79 commented on DAhmetov/lib/interpret.ml
> +  let extend_env arg_name arg_value env = KeyMap.add arg_name arg_value env
Согласен, длинно

2024-03-14 16:51 UTC, Lesh79 commented on DAhmetov/demos/demoInterpret.t
> +  > EOF
Добавил то что вы просили 😇

2024-03-18 10:23 UTC, merged