mini-ML | Shestakov Dmitrii
Kakadu/fp2023 pull request #149
Opened 2024-03-31 19:37 UTC by wokuparalyzed

Da, мне было страшно.... но я это сDелал.

2024-04-07 10:20 UTC, Kakadu requested changes
Для начала неплохо

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +        false |> List.fold_left (fun f t -> ( || ) (helper f t)) f ts
наверное, пайп излишний тут

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +      |> List.filter_map (fun id -> id)
Я не совсем понял, что значат Some и None. У Вас уже есть же возомжность отслеживать ошибки в монаде.

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +        | _ -> fail "Infer fail"
по-моему Вы искусственно ввели ошибочный случай, и теперь его надо обрабатывать. нехорошо

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +        |> Patterns.pattern_infer
снова Pipe не понятно зачем. Вас F# покусал?

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +            names
Я не очень понял, что в это fold происходит

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/interpreter.ml
> +    | None -> Constr.verr @@ Format.sprintf "\"%s\" not bound" name
%S

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/interpreter.ml
> +  | CBool b, Bool d when b = d -> true
Тут можно сократить

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/interpreter.ml
> +  |> interpret_expression
снова стрёмные pipы

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/interpreter.ml
> +  let evaluated = List.map fst evaluated in
наверное, можно поэффективнее

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/parser.ml
> +  type 'a parser = input -> 'a parse_result
Вообще, задымывалось, что Вы библиотеку возьмете, а не наколенке велосипед сделаете....

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/parser.ml
> +   >>= fun value ->
let* сюда зашло бы удачно

2024-04-07 10:20 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/tests.ml
> +let s = In_channel.input_all Stdlib.stdin
Читать stdin? зачем??

2024-04-09 19:33 UTC, wokuparalyzed commented on OCamlWithWeakTypeVariables/lib/parser.ml
> +  type 'a parser = input -> 'a parse_result
¯\_(ツ)_/¯

2024-04-09 19:35 UTC, wokuparalyzed commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +        | _ -> fail "Infer fail"
Здесь этот ошибочный случай возможен, потому что мы в аст запрещаем тюплы из не более чем 2ух элементов

2024-04-09 19:36 UTC, wokuparalyzed commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +            names
Общий контекст последовательно расшираем вложенными летами

2024-04-09 19:37 UTC, wokuparalyzed commented on OCamlWithWeakTypeVariables/lib/inferencer.ml
> +      |> List.filter_map (fun id -> id)
Здесь возвращается Some, если имя из паттерна нужно ввести в env и None, если не надо

2024-04-09 19:38 UTC, wokuparalyzed commented
Я не понял что не так с CPS. Там специально пропущена скобка в демо и используется fib вместо fibk?

2024-04-10 05:22 UTC, Kakadu commented
> Я не понял что не так с CPS. Там специально пропущена скобка в демо и используется fib вместо fibk?

Там должно быть fibk, но если написана чушь, то ругательства должны помогать понять в чем чушь

2024-04-10 05:44 UTC, Kakadu commented on OCamlWithWeakTypeVariables/lib/interpreter.ml
> +  let evaluated = List.map fst evaluated in
Выше исправили, а тут нет.

2024-04-10 05:44 UTC, Kakadu commented
Я закрою глаза на этот "парсер" и пусть будет D

2024-04-10 05:44 UTC, merged