First realization of fact parser.
Kakadu/fp2023 pull request #61
Opened 2023-10-23 10:18 UTC by SurfaceYellowDuck

2023-10-29 20:59 UTC, Kakadu commented
Документация и тестовое покрытие  должны скоро появиться.

https://kakadu.github.io/fp2023/docs/Go

https://kakadu.github.io/fp2023/cov/Go

2023-10-29 20:59

2023-10-29 21:00 UTC, Kakadu commented
Linter report from 2023-10-29 21:00, for mini language Go
```
File "lib/parser.ml", line 36, characters 49-76:
36 | let str_body = many str_char >>= fun r -> return (List.fold_left ( ^ ) "" r)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Concatenating a container of strings via fold-like iteration may lead to performance issues.
File "lib/ast.mli", line 12, characters 2-14:
12 |   | StringType
       ^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'StringType' has no documentation attribute
File "lib/ast.mli", line 13, characters 2-15:
13 |   | IntegerType
       ^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'IntegerType' has no documentation attribute
File "lib/ast.mli", line 14, characters 2-15:
14 |   | BooleanType
       ^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'BooleanType' has no documentation attribute
File "lib/ast.mli", line 15, characters 2-25:
15 |   | FuncType of signature
       ^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'FuncType' has no documentation attribute
File "lib/ast.mli", line 27, characters 2-16:
27 |   | One of type'
       ^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'One' has no documentation attribute
File "lib/ast.mli", line 28, characters 2-8:
28 |   | Void
       ^^^^^^
Alert zanuda-linter: Constructor 'Void' has no documentation attribute
File "lib/ast.mli", line 32, characters 2-14:
32 |   | Int of int
       ^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'Int' has no documentation attribute
File "lib/ast.mli", line 33, characters 2-20:
33 |   | String of string
       ^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'String' has no documentation attribute
File "lib/ast.mli", line 34, characters 2-16:
34 |   | Bool of bool
       ^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'Bool' has no documentation attribute
File "lib/ast.mli", line 38, characters 2-9:
38 |   | Minus
       ^^^^^^^
Alert zanuda-linter: Constructor 'Minus' has no documentation attribute
File "lib/ast.mli", line 39, characters 2-12:
39 |   | Asterisk
       ^^^^^^^^^^
Alert zanuda-linter: Constructor 'Asterisk' has no documentation attribute
File "lib/ast.mli", line 40, characters 2-9:
40 |   | Equal
       ^^^^^^^
Alert zanuda-linter: Constructor 'Equal' has no documentation attribute
File "lib/ast.mli", line 44, characters 2-9:
44 |   | Minus (* -expr *)
       ^^^^^^^
Alert zanuda-linter: Constructor 'Minus' has no documentation attribute
File "lib/ast.mli", line 45, characters 2-7:
45 |   | Not (* !expr *)
       ^^^^^
Alert zanuda-linter: Constructor 'Not' has no documentation attribute
File "lib/ast.mli", line 49, characters 2-21:
49 |   | Const of constant
       ^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'Const' has no documentation attribute
File "lib/ast.mli", line 50, characters 2-24:
50 |   | Identifier of string
       ^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'Identifier' has no documentation attribute
File "lib/ast.mli", line 51, characters 2-58:
51 |   | BinaryOp of expression * binary_operation * expression (* (a < b) *)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'BinaryOp' has no documentation attribute
File "lib/ast.mli", line 52, characters 2-37:
52 |   | UnaryOp of (unaryop * expression) (* unop expr *)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'UnaryOp' has no documentation attribute
File "lib/ast.mli", line 53, characters 2-43:
53 |   | FunCall of expression * expression list
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'FunCall' has no documentation attribute
File "lib/ast.mli", line 60, characters 2-47:
60 |   | FuncTopLevelDeclaration of func_declaration
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'FuncTopLevelDeclaration' has no documentation attribute
File "lib/ast.mli", line 61, characters 2-45:
61 |   | VarTopLevelDeclaration of var_declaration
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'VarTopLevelDeclaration' has no documentation attribute
File "lib/ast.mli", line 67, characters 2-40:
67 |   | Ifstmt of expression * block * block
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'Ifstmt' has no documentation attribute
File "lib/ast.mli", line 68, characters 2-40:
68 |   | ReturnStatement of expression option
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'ReturnStatement' has no documentation attribute
File "lib/ast.mli", line 69, characters 2-28:
69 |   | StatementsBlock of block
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Constructor 'StatementsBlock' has no documentation attribute
File "lib/ast.mli", lines 11-29, characters 0-39:
11 | type type' =
12 |   | StringType
13 |   | IntegerType
14 |   | BooleanType
15 |   | FuncType of signature
...
26 | and ret_typ =
27 |   | One of type'
28 |   | Void
29 | [@@deriving show { with_path = false }]
Alert zanuda-linter: Unneeded mutual recursion detected in these type declarations. It's recommended to rewrite 'arg' as follows:
                     type arg = (string * type')[@@deriving
                                                  show { with_path = false }]
File "lib/ast.mli", lines 48-70, characters 0-39:
48 | type expression =
49 |   | Const of constant
50 |   | Identifier of string
51 |   | BinaryOp of expression * binary_operation * expression (* (a < b) *)
52 |   | UnaryOp of (unaryop * expression) (* unop expr *)
...
67 |   | Ifstmt of expression * block * block
68 |   | ReturnStatement of expression option
69 |   | StatementsBlock of block
70 | [@@deriving show { with_path = false }]
Alert zanuda-linter: Unneeded mutual recursion detected in these type declarations. It's recommended to rewrite 'var_declaration', 'block', 'func_declaration', 'top_level_declaration', 'statements' as follows:
                     type var_declaration = (string * expression)
                     type block = statements list
                     type func_declaration = (string * signature * block)
                     type top_level_declaration =
                       | FuncTopLevelDeclaration of func_declaration 
                       | VarTopLevelDeclaration of var_declaration [@@deriving
                                                                    show
                                                                    {
                                                                    with_path
                                                                    = false
                                                                    }]
                     type statements =
                       | Ifstmt of expression * block * block 
                       | ReturnStatement of expression option 
                       | StatementsBlock of block [@@deriving
                                                    show
                                                      { with_path = false }]
```

2023-10-30 18:33 UTC, Kakadu commented on Go/lib/parser.ml
> +(** Copyright 2021-2023, Nikita Lukonenko and Furetur *)
А каким образом Go стал на двоих?

`(** Copyright 2021-2023, Nikita Lukonenko and Furetur *)`

2023-10-30 19:02 UTC, Kakadu requested changes
Замечания линтера и прочее

2023-10-30 20:21 UTC, SurfaceYellowDuck commented on Go/lib/parser.ml
> +(** Copyright 2021-2023, Nikita Lukonenko and Furetur *)
Задача выполнялась одним человеком, но я указал автора, чей код я подсматривал при решении.

2024-01-16 16:12 UTC, merged