Add parser with tests
Kakadu/fp2023 pull request #64
Opened 2023-10-29 12:59 UTC by Parzival-05

2023-10-29 13:03 UTC, Kakadu commented
Документация и тестовое покрытие  должны скоро появиться.

https://kakadu.github.io/fp2023/docs/OCaml_ExtensibleVariantTypes

https://kakadu.github.io/fp2023/cov/OCaml_ExtensibleVariantTypes

2023-10-29 13:02

2023-10-29 13:03 UTC, Kakadu commented
Linter report from 2023-10-29 13:03, for mini language OCaml_ExtensibleVariantTypes
```
File '_build/default/lib/parser.ml' doesn't have corresponding .mli interface
File '_build/default/lib/tests.ml' doesn't have corresponding .mli interface

File "lib/parser.ml", line 159, characters 72-81:
159 | let parse_identifier_to_expr = parse_identifier >>= fun id -> return @@ eid @@ id
                                                                              ^^^^^^^^^
Alert zanuda-linter: Extranous `@@`.
File "lib/parser.ml", line 167, characters 28-52:
167 |   >>= fun ident_list_res -> return @@ ident_list_res
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter: Extranous `@@`.
File "lib/parser.ml", line 202, characters 17-30:
202 |   >>= fun res -> return @@ res
                       ^^^^^^^^^^^^^
Alert zanuda-linter: Extranous `@@`.
File "lib/parser.ml", line 321, characters 27-35:
321 |      | ": end_of_input" -> failwith "Can't parse decl"
                                 ^^^^^^^^
Alert zanuda-linter: Using `failwith` (or `assert false`) usually is a clue that a corner case is not being handled properly. To report errors we recommend using error monad instead. In princliple, these construction are OK for temporary work-in-progress code, but in release they should be eliminated
File "lib/parser.ml", line 322, characters 12-20:
322 |      | _ -> failwith msg)
                  ^^^^^^^^
Alert zanuda-linter: Using `failwith` (or `assert false`) usually is a clue that a corner case is not being handled properly. To report errors we recommend using error monad instead. In princliple, these construction are OK for temporary work-in-progress code, but in release they should be eliminated
File "lib/ast.ml", lines 12-31, characters 0-39:
12 | type bin_op =
13 |   | Add (* + *)
14 |   | Sub (* - *)
15 |   | Mul (* * *)
16 |   | Div (* / *)
...
28 |   | Plus (* ~+ *)
29 |   | Minus (* ~- *)
30 |   | Not (* ~not *)
31 | [@@deriving show { with_path = false }]
Alert zanuda-linter: Unneeded mutual recursion detected in these type declarations. It's recommended to rewrite 'unary_op' as follows:
                     type unary_op =
                       | Plus 
                       | Minus 
                       | Not [@@deriving show { with_path = false }]
File "lib/ast.ml", lines 38-59, characters 0-66:
38 | type expr =
39 |   | EEmpty (* Empty expression *)
40 |   | EConst of const (* Const. Examples: 100; true; "hello, world!" *)
41 |   | EBinop of
42 |       expr * bin_op * expr (* Binary operation. Examples: 2 + 2; (234 * 234) + 234*)
...
56 | [@@deriving eq, show { with_path = false }]
57 | 
58 | and bind = DLet of rec_flag * ident * expr [@@deriving eq, show { with_path = false }]
59 | and decl = bind * expr [@@deriving eq, show { with_path = false }]
Alert zanuda-linter: Unneeded mutual recursion detected in these type declarations. It's recommended to rewrite 'rec_flag', 'bind', 'decl' as follows:
                     type rec_flag =
                       | Recursive 
                       | Not_recursive [@@deriving
                                         (eq, (show { with_path = false }))]
                     type bind =
                       | DLet of rec_flag * ident * expr [@@deriving
                                                           (eq,
                                                             (show
                                                                {
                                                                  with_path =
                                                                    false
                                                                }))]
                     type decl = (bind * expr)[@@deriving
                                                (eq,
                                                  (show { with_path = false }))]
```

2023-10-29 13:18 UTC, Kakadu commented
Документация и тестовое покрытие  должны скоро появиться.

https://kakadu.github.io/fp2023/docs/OCaml_ExtensibleVariantTypes

https://kakadu.github.io/fp2023/cov/OCaml_ExtensibleVariantTypes

2023-10-29 13:18

2023-10-29 13:18 UTC, Kakadu commented
Linter report from 2023-10-29 13:18, for mini language OCaml_ExtensibleVariantTypes
```
File '_build/default/lib/parser.ml' doesn't have corresponding .mli interface
File '_build/default/lib/tests.ml' doesn't have corresponding .mli interface

File "lib/parser.ml", line 318, characters 27-35:
318 |      | ": end_of_input" -> failwith "Can't parse decl"
                                 ^^^^^^^^
Alert zanuda-linter: Using `failwith` (or `assert false`) usually is a clue that a corner case is not being handled properly. To report errors we recommend using error monad instead. In princliple, these construction are OK for temporary work-in-progress code, but in release they should be eliminated
File "lib/parser.ml", line 319, characters 12-20:
319 |      | _ -> failwith msg)
                  ^^^^^^^^
Alert zanuda-linter: Using `failwith` (or `assert false`) usually is a clue that a corner case is not being handled properly. To report errors we recommend using error monad instead. In princliple, these construction are OK for temporary work-in-progress code, but in release they should be eliminated
File "lib/ast.ml", lines 38-58, characters 0-86:
38 | type expr =
39 |   | EEmpty (* Empty expression *)
40 |   | EConst of const (* Const. Examples: 100; true; "hello, world!" *)
41 |   | EBinop of
42 |       expr * bin_op * expr (* Binary operation. Examples: 2 + 2; (234 * 234) + 234*)
...
55 |   | Not_recursive
56 | [@@deriving eq, show { with_path = false }]
57 | 
58 | and bind = DLet of rec_flag * ident * expr [@@deriving eq, show { with_path = false }]
Alert zanuda-linter: Unneeded mutual recursion detected in these type declarations. It's recommended to rewrite 'rec_flag', 'bind' as follows:
                     type rec_flag =
                       | Recursive 
                       | Not_recursive [@@deriving
                                         (eq, (show { with_path = false }))]
                     type bind =
                       | DLet of rec_flag * ident * expr [@@deriving
                                                           (eq,
                                                             (show
                                                                {
                                                                  with_path =
                                                                    false
                                                                }))]
```

2023-10-29 14:46 UTC, Kakadu requested changes
А где хотя бы cram test с факториалом?

2023-10-29 14:46 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/ast.ml
> +  | EParams of expr list
Это какая-то дичь, которая, надеюсь, постепенно исчезнет.

2023-10-29 14:46 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/ast.ml
> +[@@deriving eq, show { with_path = false }]
А eq правда везде надо?

2023-10-29 14:46 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/parser.ml
> +  ; "string"
Нет такого ключевого слова.

2023-10-29 23:23 UTC, Parzival-05 commented on OCaml_ExtensibleVariantTypes/lib/ast.ml
> +[@@deriving eq, show { with_path = false }]
Да. rec_flag есть в типе decl.

2023-10-30 00:12 UTC, Kakadu commented
Документация и тестовое покрытие  должны скоро появиться.

https://kakadu.github.io/fp2023/docs/OCaml_ExtensibleVariantTypes

https://kakadu.github.io/fp2023/cov/OCaml_ExtensibleVariantTypes

2023-10-30  0:12

2023-10-30 00:13 UTC, Kakadu commented
Linter report from 2023-10-30  0:13, for mini language OCaml_ExtensibleVariantTypes
```
File '_build/default/lib/parser.ml' doesn't have corresponding .mli interface
File '_build/default/lib/tests.ml' doesn't have corresponding .mli interface

File "lib/tests.ml", line 3, characters 0-49:
3 | (** SPDX-License-Identifier: LGPL-3.0-or-later *)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert zanuda-linter:  First item in file should be a documentation comment with copyright information. For example:
            (** Copyright 2021-2022, Winnie Pooh et al. *)
File "lib/tests.ml", line 5, characters 0-0:
Alert zanuda-linter: Second item in file should be a documentation comment with correct license information. For example:
           (** SPDX-License-Identifier: LGPL-3.0-or-later *)
```

2023-10-30 00:20 UTC, Kakadu commented
Документация и тестовое покрытие  должны скоро появиться.

https://kakadu.github.io/fp2023/docs/OCaml_ExtensibleVariantTypes

https://kakadu.github.io/fp2023/cov/OCaml_ExtensibleVariantTypes

2023-10-30  0:20

2023-10-30 00:21 UTC, Kakadu commented
Linter report from 2023-10-30  0:21, for mini language OCaml_ExtensibleVariantTypes
```
File '_build/default/lib/parser.ml' doesn't have corresponding .mli interface
File '_build/default/lib/tests.ml' doesn't have corresponding .mli interface
```

2023-10-30 19:08 UTC, Kakadu commented on OCaml_ExtensibleVariantTypes/lib/tests.ml
> +    "let a = fun (x,y) (z,w) k-> (x,y)"
Давайте впредь через cram

2023-10-30 19:33 UTC, merged

2023-10-30 19:37 UTC, Kakadu commented
Документация и тестовое покрытие  должны скоро появиться.

https://kakadu.github.io/fp2023/docs/OCaml_ExtensibleVariantTypes

https://kakadu.github.io/fp2023/cov/OCaml_ExtensibleVariantTypes

2023-10-30 19:37

2023-10-30 19:37 UTC, Kakadu commented
Linter report from 2023-10-30 19:37, for mini language OCaml_ExtensibleVariantTypes
```
File '_build/default/lib/parser.ml' doesn't have corresponding .mli interface
File '_build/default/lib/tests.ml' doesn't have corresponding .mli interface
```