Implementation of the interpreter
Kakadu/fp2023 pull request #93
Opened 2023-12-20 03:15 UTC by YazoonDinalt

Added implementation of interpreter, type checker, modified ast and parser

2024-02-29 13:00 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.ml
> +    | CNil -> VNone
А почему оно рекурсивное?

2024-02-29 13:02 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.ml
> +          | LetActExpr (fl, _) when List.length fl = 1 ->
Гварды тут неэффективны и не нужны

2024-03-01 05:38 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  (** let sq x = x * x , first bool - is rec or not, second bool - is act pat or not *)
Я  сначала пробовал реализовать одним способом, и у меня все let хранились в одном месте, один из bool отвечал за то, actPat это или нет, потом переделал, но забыл поменять комментарий, исправил

2024-03-01 05:38 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  | CaseExpr of name * expr list (** (|Even|Odd||)*)
добавил пояснение

2024-03-01 05:39 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  | VCases of name * value option
добавил пояснений

2024-03-01 05:39 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +(** for interpret *)
Посчитал, что нахождение его здесь - самое логичное

2024-03-01 05:39 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/errorinter.ml
> +  | Empty_pattern
Исправил, добавил пояснение

2024-03-01 05:40 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +    | CNil -> VNone
Если я правильно понял вопрос, то мне просто показалось это самым лаконичным решением

2024-03-01 05:41 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +          | LetActExpr (fl, _) when List.length fl = 1 ->
И в правду, бес попутал, исправил

2024-03-01 05:41 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +;;
:(

2024-03-01 05:50 UTC, YazoonDinalt commented
Вроде бы исправил замечания, type checker на active patterns я уже не реализую, на какую максимальную оценку можно претендовать с текущей работой?

2024-03-06 09:43 UTC, Kakadu reviewed
AST ни в хвост, ни в гриву

> на какую максимальную оценку можно претендовать с текущей работой
F я всегда готов поставить :)

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/ast.ml
> +  (** let (|Even|Odd|) ..., let (|Even|_|) ..., let (|Even|)... *)
По-моему, это не выражение

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/ast.ml
> +  | CaseExpr of name * expr list (** (|Even|Odd|), Some x *)
И это тоже не выглядит, как выржение.

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/ast.ml
> +  | VNone
Это не AST

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/errorinter.mli
> +  | NotImplemented
Этого быть не должно

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/inferencer.ml
> +       | CNil -> return (env, Prim "nil"))
Я всё ещё не понимаю, что такое "nil"

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.ml
> +    | None when is_constr @@ String.get key 0 -> fail (UnboundConstructor key)
Строки бывают пустые.

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.ml
> +       | _ -> fail Unreachable)
?

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.ml
> +    | CNil -> VNone
Не надо так смущать читателя

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/ast.ml
> +  | VNone
И как будет выглядет Some?

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.ml
> +;;
?

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/parser.ml
> +      <|> ((fun _ -> CBool true) <$> string "false"))
Тут нет ли опечатки?

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/typedtree.mli
> +
Имя файла не соответствует содержиомму.

2024-03-06 09:43 UTC, Kakadu commented on FSharpActivePatterns/lib/typedtree.ml
> +  pp_print_list ~pp_sep:(fun ppf _ -> fprintf ppf sep) (fun ppf ty -> helper ppf ty) l
длинно

2024-03-07 00:18 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/typedtree.ml
> +  pp_print_list ~pp_sep:(fun ppf _ -> fprintf ppf sep) (fun ppf ty -> helper ppf ty) l
Исправлено

2024-03-07 00:18 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/parser.ml
> +      <|> ((fun _ -> CBool true) <$> string "false"))
И в правду, есть опечатка, исправил

2024-03-07 00:20 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  (** let (|Even|Odd|) ..., let (|Even|_|) ..., let (|Even|)... *)
LetACtExpr? Там же дальше будет выражение, добавил пояснение

2024-03-07 00:22 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  | VNone
Исправлено, перенёс в imterpret

2024-03-07 00:22 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/errorinter.mli
> +  | NotImplemented
Чего именно и почему?

2024-03-07 00:24 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/inferencer.ml
> +       | CNil -> return (env, Prim "nil"))
В F# нет как такого названия для пустого списка, сделал как в Ocaml, заменил на "[]"

2024-03-07 00:26 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +       | _ -> fail Unreachable)
А что здесь не так?

2024-03-07 00:26 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  | VNone
Изменено

2024-03-07 00:29 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/typedtree.mli
> +
Изменил, надеюсь, сейчас нормально

2024-03-07 00:35 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +;;
Не очень понимаю почему это плохо, если честно

2024-03-07 00:36 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +    | CNil -> VNone
Мне заменить или можно оставить так как есть? Там будет либо везде передаваться eval, либо это всё упаковать в eval без разбивки на отдельные части

2024-03-07 00:55 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +    | None when is_constr @@ String.get key 0 -> fail (UnboundConstructor key)
И то верно, исправил, добавил ошибку

2024-03-07 01:34 UTC, YazoonDinalt commented
Всё исправил, надеюсь, сейчас всё хорошо

2024-03-10 12:05 UTC, Kakadu requested changes
Сюда бы ещё демки на CPSный факториал с неподвижной точкой, и на замыкания.

2024-03-10 12:05 UTC, Kakadu commented on FSharpActivePatterns/lib/interpret.mli
> +  | VLetWAPat of name * value (** Let without active patterns, let x y = y * 5 *)
А как у вас замыкания представляются?

2024-03-22 12:26 UTC, YazoonDinalt commented
А есть ли возможность получить любую оценку выше F и не доделывать это? Сейчас сильная нехватка времени, а допуск в каком-то виде получить очень хочется :(

2024-03-25 10:30 UTC, Kakadu commented
> А есть ли возможность получить любую оценку выше F и не доделывать это? Сейчас сильная нехватка времени, а допуск в каком-то виде получить очень хочется :(

У вас AST неадекватное. Переделывайте.

2024-03-26 21:51 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/errorinter.mli
> +  | NotImplemented
А как тогда пометить то, что я уже не смогу реализовать?

2024-03-26 21:51 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/inferencer.ml
> +       | CNil -> return (env, Prim "nil"))
Исправил

2024-03-26 21:51 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +       | _ -> fail Unreachable)
Исправил

2024-03-26 21:52 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  (** let (|Even|Odd|) value = ..., let (|Even|_|) value =  ..., let (|Even|) value = ... *)
Почему? Это же выражения

2024-03-26 21:52 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/inferencer.ml
> +      let* env, ty2 = pattern_helper env (List.hd_exn (List.tl_exn a)) in
Исправил

2024-03-26 21:53 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/inferencer.ml
> +    | Case _ -> fail NotImplemented
Я уже не реализую проверку типов на активные паттерны, поэтому там для этого стоит NotImplemented

2024-03-26 21:55 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/interpret.ml
> +;;
Я вынес тесты в отдельный файл, но не соглашусь, что в интепретаторе мусорные тесты, там все проверяется по минимуму, возможно это можно было написать короче, если дело в этом

2024-03-26 21:57 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/ast.ml
> +  (** let (|Even|Odd|) value = ..., let (|Even|_|) value =  ..., let (|Even|) value = ... *)
Если речь про LetActExpr, то это выражение, почти let, но для активных паттернов

2024-03-26 22:00 UTC, YazoonDinalt commented on FSharpActivePatterns/lib/inferencer.ml
> +    | LetExpr (is_rec, name, expr) ->
не очень понимаю что имеется в виду, если честно

2024-04-01 18:31 UTC, YazoonDinalt commented
> Сюда бы ещё демки на CPSный факториал с неподвижной точкой, и на замыкания.
Добавил демо тесты на это

2024-04-07 08:24 UTC, Kakadu requested changes
У вас не корректное AST в том смысле, что можно записать бессмысленные значения.
Попробуйте написать pretty-printer, чтобы увидеть что не так.
Так же у Вас будут проблемы с написанием библиотеки для работы со списками, некоторые функции просто не получится написать. Это надо исправлять и в паттернах, и в выражениях

2024-04-07 08:27 UTC, Kakadu commented on FSharpActivePatterns/lib/inferencer.ml
> +    | Case _ -> fail NotImplemented
Это совершенно не очевидно из того, что написано. Надо это писать явно

2024-04-07 08:27 UTC, Kakadu commented on FSharpActivePatterns/lib/inferencer.ml
> +      let* env, ty2 = pattern_helper env (List.hd_exn (List.tl_exn a)) in
Разве?

2024-04-10 06:41 UTC, Kakadu commented
У вас были проблемы c AST, вы его не поменяли и затребовали повторное ревью? На что вы рассчитываете?

2024-04-11 17:02 UTC, merged