Fix parser and add remaining features
Kakadu/fp2023 pull request #97
Opened 2023-12-28 01:19 UTC by Salvatore112

2023-12-31 10:29 UTC, Kakadu requested changes

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/ast.mli
> +  | FString of f_string_type list [@ocaml.doc " F string "]
А почему в одном месте одни комменты, а в другом другие?

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/interpreter.ml
> +    | _ -> "Interpretation Error"
Мы э это обсуждали уже?

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/interpreter.ml
> +        let temp_env = { env with functions = env.functions @ [ fetchedMethod ] } in
Какая эффективная реализация

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/interpreter.ml
> +      | _ -> error "unexpected statement"
Было бы неплохо знать какая именно и почему

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/parser.mli
> +(** Copyright 2021-2022, Averin Pavel *)
А зачем ?

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/parser.mli
> +val is_whitespace_or_eol : char -> bool
А почему все функции публичные?

2023-12-31 10:29 UTC, Kakadu commented on Python/lib/tests.ml
> +let%test _ =
По-моему вы заигнорили все что я рассказывал на паре про три вида тестов и строковые литералы. Переделывайте

2023-12-31 22:48 UTC, Salvatore112 commented on Python/lib/ast.mli
> +  | FString of f_string_type list [@ocaml.doc " F string "]
Линтер ругался, пока я не сделал, как он просил: 
![image](https://github.com/Kakadu/fp2023/assets/113641510/123650d0-d400-4da6-b4ea-80a3b2a71495)

2023-12-31 22:50 UTC, Salvatore112 commented on Python/lib/parser.mli
> +(** Copyright 2021-2022, Averin Pavel *)
Тут с линтера скопировал криво. Поправлю.
![image](https://github.com/Kakadu/fp2023/assets/113641510/306abe37-85d4-4b86-9fb6-109a45349961)

2024-01-03 06:36 UTC, Salvatore112 commented on Python/lib/interpreter.ml
> +        let temp_env = { env with functions = env.functions @ [ fetchedMethod ] } in
Как смог сделал 😔. Вы вроде говорили что требований к эффектиновсти нет.

2024-01-03 18:30 UTC, Kakadu commented on Python/lib/tests.ml
> +let%test _ =
Типа порезолвили, чтобы я забыл? Как там в фильме было: "Профессор лопух, аппаратура при нём"

2024-01-03 18:32 UTC, Kakadu commented on Python/lib/interpreter.ml
> +        let temp_env = { env with functions = env.functions @ [ fetchedMethod ] } in
Это не означает, что можно явный гавнокод писать.

2024-01-03 21:54 UTC, Kakadu commented on Python/lib/interpreter.ml
> +      | _ -> error "Interpretation error"
А почему всё остальное ошибка? Какие случаи остались не разобраны?

2024-01-03 21:54 UTC, Kakadu commented on Python/lib/interpreter.ml
>      get_env env
Что-то очень сложное написано.

2024-01-03 21:56 UTC, Kakadu commented on Python/demos/adding_class_to_env_test.ml
> +let unpacker (Ok x) = x
Почему отсюда ползут предупреждения компилятора?

2024-01-03 21:57 UTC, Kakadu commented on Python/demos/anon_func_test.ml
> +;;
На анонимные функции очень бедные тесты. Хочу факториал/фибоначчи с комбинатором неподвижной точки и CPS.

2024-01-03 22:10 UTC, Salvatore112 commented on Python/lib/tests.ml
> +let%test _ =
Я же исправил в [Salvatore112:master](https://github.com/Kakadu/fp2023/pull/97/commits/2e085aad2f789a7e1b0153a55eb07dde6fa4ee51)

2024-01-04 12:09 UTC, Salvatore112 commented on Python/lib/interpreter.ml
> +      | _ -> error "Interpretation error"
![image](https://github.com/Kakadu/fp2023/assets/113641510/b7cf9867-b328-495c-ab1b-a6f5ad11f0b7)
Подобные случаи, пользователь делает тут что-то странное

2024-01-11 10:39 UTC, Salvatore112 commented on Python/demos/anon_func_test.ml
> +;;
Здравствуйте, дней 5 пытался сделать что-то менее бедное, не получилось... Вы можете подсказать, дать идей, без переписывания всего с нуля, или можно оставить как есть? Остальные замечания вроде все поправил.

2024-01-11 11:59 UTC, Kakadu commented
> Здравствуйте, дней 5 пытался сделать что-то менее бедное, не получилось... Вы можете подсказать, дать идей, без переписывания всего с нуля, или можно оставить как есть? Остальные замечания вроде все поправил.

Предлагаю максимум С и идете учить теорию

2024-01-11 12:00 UTC, Kakadu commented on Python/demos/anon_func_test.ml
> +;;
> Здравствуйте, дней 5 пытался сделать что-то менее бедное, не получилось... Вы можете подсказать, дать идей, без переписывания всего с нуля, или можно оставить как есть? Остальные замечания вроде все поправил.

Предлагаю максимум С и идете учить теорию

2024-01-11 12:08 UTC, Salvatore112 commented
Чего не хватает для B и A? Или только из-за анонимных так?

2024-01-11 12:11 UTC, Salvatore112 commented
> Чего не хватает для B и A? Или только из-за анонимных так?

2024-01-11 12:12 UTC, Salvatore112 commented
> > Здравствуйте, дней 5 пытался сделать что-то менее бедное, не получилось... Вы можете подсказать, дать идей, без переписывания всего с нуля, или можно оставить как есть? Остальные замечания вроде все поправил.
> 
> Предлагаю максимум С и идете учить теорию

Чего не хватает для B и A? Или только из-за анонимных так получилось?

2024-01-12 11:31 UTC, Kakadu commented on Python/demos/adding_class_to_env_test.ml
> +     | Error _ -> print_string "change print func test failed")
copypaste

2024-01-12 12:01 UTC, Kakadu commented on Python/demos/adding_class_to_env_test.ml
> +  let rec print_classes : environment list -> unit = function
iter

2024-01-12 14:37 UTC, Kakadu commented on Python/lib/ast.ml
> +  | Nil
Одни и те же значения представимы дважды

2024-01-12 21:09 UTC, merged